version: '3.9'
services:
  api:
    build: .
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - NPM_CONFIG_PRODUCTION=${NPM_CONFIG_PRODUCTION:-false}
      - DB_HOST=${DB_HOST:-postgres}
      - DB_PORT=${DB_PORT:-5432}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
    ports:
      - "${PORT:-3000}:3000"
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/status"]
      interval: 30s
      timeout: 10s
      retries: 5
